In [46]:
import numpy as np

In [39]:
#1 Create a numpy array containing the numbers from 1 to 10

In [62]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
# Reshape the array into a 2x5 matrix

In [48]:
matrix = arr.reshape(2,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#2 Create a numpy array containing the numbers from 1 to 20

In [49]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Extract elements from index 5 to index 15

In [50]:
result = arr[5:16]
print(result)

[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#3 Create a NumPy array containing numbers from 1 to 20

In [51]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#Calculate Mean

In [52]:
mean = np.mean(arr)
print(mean)

10.5


In [ ]:
#Calculate Median

In [53]:
median = np.median(arr)
print(median)

10.5


In [ ]:
#Calculate Standard Deviation

In [54]:
std_dev = np.std(arr)
print(std_dev)

5.766281297335398


In [ ]:
#4 Create a 2D array of shape (3,4)

In [55]:
a = np.array([[10,20,30,40],
               [50,60,70,80],
               [90,100,110,120]])
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [ ]:
# Create a 1D array of shape (4,)

In [56]:
b = [1,2,3,4]
print(b)

[1, 2, 3, 4]


In [ ]:
# Subtract y from each row of x

In [57]:
result = a - b
print(result)

[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


In [21]:
import pandas as pd

In [ ]:
#5 create a dataframe

In [58]:
data = {
    "Name" : ["Amy","Kajal","Diya","Thushita","Delna","Saujanya","Bargavi","Jane","Aswathy","Ryan Gosling"],
    "Age" : [30,22,23,21,24,26,89,19,34,48],
    "Gender" : ["Female","Female","Female","Female","Female","Female","Female","Female","Female","Male"]
}
df = pd.DataFrame(data)
print(df)

           Name  Age  Gender
0           Amy   30  Female
1         Kajal   22  Female
2          Diya   23  Female
3      Thushita   21  Female
4         Delna   24  Female
5      Saujanya   26  Female
6       Bargavi   89  Female
7          Jane   19  Female
8       Aswathy   34  Female
9  Ryan Gosling   48    Male


In [24]:
#Add a new coloumn as "occupation"

In [59]:
df["Occupation"]= ["Programmer", "Manager", "Analyst",
    "Programmer", "Manager", "Analyst",
    "Programmer", "Manager", "Analyst",
    "Programmer"]
print(df)

           Name  Age  Gender  Occupation
0           Amy   30  Female  Programmer
1         Kajal   22  Female     Manager
2          Diya   23  Female     Analyst
3      Thushita   21  Female  Programmer
4         Delna   24  Female     Manager
5      Saujanya   26  Female     Analyst
6       Bargavi   89  Female  Programmer
7          Jane   19  Female     Manager
8       Aswathy   34  Female     Analyst
9  Ryan Gosling   48    Male  Programmer


In [27]:
#Select the rows of the dataframe where the age is greater than or equal to 30.

In [60]:
ages_df = df[df["Age"] >= 30]
print(ages_df)

           Name  Age  Gender  Occupation
0           Amy   30  Female  Programmer
6       Bargavi   89  Female  Programmer
8       Aswathy   34  Female     Analyst
9  Ryan Gosling   48    Male  Programmer


In [ ]:
#save the DataFrame into csv file

In [37]:
df.to_csv("employees.csv", index=False)

In [ ]:
#read the csv file

In [38]:
new_df =pd.read_csv("employees.csv")

In [61]:
print(new_df)

           Name  Age  Gender  Occupation
0           Amy   30  Female  Programmer
1         Kajal   22  Female     Manager
2          Diya   23  Female     Analyst
3      Thushita   21  Female  Programmer
4         Delna   24  Female     Manager
5      Saujanya   26  Female     Analyst
6       Bargavi   89  Female  Programmer
7          Jane   19  Female     Manager
8       Aswathy   34  Female     Analyst
9  Ryan Gosling   48    Male  Programmer
