1.Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column.

In [2]:
#import libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Load dataset

In [3]:
df = pd.read_csv("winequality-red.csv",sep=";")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5


In [4]:
#check missing values

In [5]:
print(df.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


In [6]:
df = df.fillna(df.mean(numeric_only=True))

In [7]:
print(df.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


2.Extract the following columns as vectors: alcohol,citric acid. 

In [8]:
alcohol = df["alcohol"].values
citric_acid = df["citric acid"].values

print("Alcohol vector:")
print(alcohol)

print("\nCitric Acid vector:")
print(citric_acid)

Alcohol vector:
[ 9.4  9.8  9.8 ... 11.  10.2 11. ]

Citric Acid vector:
[0.   0.   0.04 ... 0.13 0.12 0.47]


3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.

In [ ]:
# Select two features

In [9]:
X = df[["alcohol", "density"]].values

print("Feature Matrix:")
print(X)

Feature Matrix:
[[ 9.4      0.9978 ]
 [ 9.8      0.9968 ]
 [ 9.8      0.997  ]
 ...
 [11.       0.99574]
 [10.2      0.99547]
 [11.       0.99549]]


In [ ]:
# Calculate covariance matrix

In [10]:
cov_matrix = np.cov(X.T)

print("\nCovariance Matrix:")
print(cov_matrix)


Covariance Matrix:
[[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]


4. Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.

In [11]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[1.13564827e+00 2.68507580e-06]

Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]


In [ ]:
# Sort eigenvalues from largest to smallest

In [12]:
idx = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print("Sorted Eigenvalues:")
print(eigenvalues)

print("\nCorresponding Eigenvectors:")
print(eigenvectors)

Sorted Eigenvalues:
[1.13564827e+00 2.68507580e-06]

Corresponding Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]


5.Which wine quality is most common in the dataset? How can you interpret the
distribution of wine quality scores?

In [13]:
quality_counts = df["quality"].value_counts().sort_index()

print(quality_counts)

quality
3     10
4     53
5    681
6    638
7    199
8     18
Name: count, dtype: int64


In [14]:
most_common_quality = df["quality"].mode()[0]

print("Most common wine quality:", most_common_quality)

Most common wine quality: 5


In [16]:
#interpretation